Test uri
nfcim/ndef pull request #11
Opened 2021-08-19 21:16 UTC by Chever-John

There's one **change** I can't tell if it's needed.
`void testGenerate(List<String> hexStrings, List<List<NDEFRecord>> messages) {
  for (int i = 0; i < hexStrings.length; i++) {
    var j = i;
    if (hexStrings[j] == ' ') {
      j++;
      assert(encodeNdefMessage(messages[i]).toHexString() == hexStrings[j]);
    }
  }
}`

2021-08-19 21:16 UTC, Chever-John commented
> 
`
void testGenerate(List<String> hexStrings, List<List<NDEFRecord>> messages) {
  for (int i = 0; i < hexStrings.length; i++) {
    var j = i;
    if (hexStrings[j] == ' ') {
      j++;
      assert(encodeNdefMessage(messages[i]).toHexString() == hexStrings[j]);
    }
  }
}
`

2021-08-20 11:58 UTC, Harry-Chen reviewed
除了剥离两个测试之外，还有什么工作呢？它和原来的测试对应的有什么区别呢？

2021-08-20 11:58 UTC, Harry-Chen commented on test/test_uri.dart
> +  test('ndef message with ', () {
这句话没写完？

2021-09-14 15:35 UTC, Harry-Chen requested changes
Please fix your code according to my comments.

2021-09-14 15:35 UTC, Harry-Chen commented on test/test_examples_of_records/device_information_test.dart
> +        var value = [
Replace with hex string

2021-09-14 15:35 UTC, Harry-Chen commented on test/test_examples_of_records/uri_test.dart
> +          equals([
Replace with hex string

2021-09-17 17:16 UTC, Chever-John commented on test/test_examples_of_records/device_information_test.dart
> +        var value = [
Got it!

2021-09-17 17:16 UTC, Chever-John commented on test/test_examples_of_records/uri_test.dart
> +          equals([
Got it!

2021-09-19 18:00 UTC, closed without merging