Null Safety Support 1.0
nfcim/ndef pull request #8
Opened 2021-08-05 05:50 UTC by Chever-John

1. remove some annotations.
2. null-safety supported.
3. no '!' in static functions.

2021-08-05 08:30 UTC, Harry-Chen requested changes
Almost LGTM. Please modify according to my comments to make the code neater & cleaner.

2021-08-05 08:30 UTC, Harry-Chen commented on lib/record.dart
> +      TypeNameFormat? tnf, Uint8List? type, Uint8List? payload,
Seems parameters such as `tnf`, `type` and `payload` need not to be nullable.

2021-08-05 08:30 UTC, Harry-Chen commented on lib/record/bluetooth.dart
> +    str += "address=${(address?.address) == null ? " address is null " : address?.address} ";
Replace with cleaner code:

```suggestion
    str += "address=${address?.addresss ?: '(null)'} ";
```

2021-08-05 08:30 UTC, Harry-Chen commented on lib/record/bluetooth.dart
> +  /// TODO: delete '!'
Note this

2021-08-05 08:30 UTC, Harry-Chen commented on lib/record/mime.dart
> +    str += "payload=${(payload?.toHexString()) ==  null ? " payload is null " : payload?.toHexString()}";
See above, replace with '?:' operator

2021-08-05 08:30 UTC, Harry-Chen commented on lib/record/wellknown.dart
> +    str += "payload=${(payload?.toHexString()) ==  null ? " payload is null " : payload?.toHexString()}";
Replace with `?:`

2021-08-05 15:51 UTC, Chever-John commented on lib/record/wellknown.dart
> +    str += "payload=${(payload?.toHexString()) ==  null ? " payload is null " : payload?.toHexString()}";
have changed to ??

2021-08-06 06:56 UTC, Harry-Chen approved these changes
LGTM now. Need some tiny fixes.

2021-08-06 06:57 UTC, merged